name: iot-platform

services:
  app:
    build: .
    image: iot-platform:app
    ports:
      - "21000:3000"
    depends_on:
      - mongo
      - mosquitto
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/iot-platform
      - MQTT_HOST=mosquitto
    networks:
      - default

  mongo:
    build: docker/mongo
    image: iot-platform:mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - default

  mosquitto:
    image: eclipse-mosquitto:1.4.8
    volumes:
      - ./docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - default

networks:
  default:
    ipam:
      config:
        - subnet: 172.50.0.0/24

volumes:
  mongo_data:
